### PR TITLE
SignUp Customer Backend Added

### PR DESCRIPTION
**Pull request by Neeraj2212**
All conflicts were solved

### CODE REVIEW

**Review by divyaprakash-Rx — COMMENTED** [review]
@Neeraj2212 Please remove client/package-lock.json. 
The main repo is in yarn.

**Comment by Neeraj2212** [comment]
Done Changes

**Comment by Neeraj2212** [comment]
And change root readme instructions if you want that everybody should use yarn instead of npm.

**Comment by divyaprakash-Rx** [comment]
> 
> 
> And change root readme instructions if you want that everybody should use yarn instead of npm.

https://github.com/dscnitp/job-provider-site/blob/master/client/README.md
It is here but missing in readme.

Alright.

**Review by divyaprakash-Rx — APPROVED** [review]

**Review by raksh543 — APPROVED** [review]

**Pull request merged**
